"""Fleet PR body formatter.

Produces publication-quality PR descriptions with changelog,
diff table, cross-references, and labor attribution.

Every PR carries provenance: what backend, model, confidence tier,
effort level, and budget mode produced the work. This data comes
from infrastructure (dispatch records + session metrics), not from
agent self-reporting.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Optional

from fleet.core.models import Commit
from fleet.core.urls import ResolvedUrls

if TYPE_CHECKING:
    from fleet.core.labor_stamp import LaborStamp


def format_pr_body(
    *,
    summary: str,
    commits: list[Commit],
    diff_stat: list[dict],
    urls: ResolvedUrls,
    task_id: str,
    task_title: str,
    agent_name: str,
    labor_stamp: Optional["LaborStamp"] = None,
) -> str:
    """Build a rich PR body from task data with labor attribution.

    Args:
        summary: What was done and why.
        commits: Parsed commits on the branch.
        diff_stat: File changes [{path, added, removed}].
        urls: Resolved URLs for all references.
        task_id: MC task ID.
        task_title: MC task title.
        agent_name: Agent that did the work.
        labor_stamp: Provenance record (backend, model, tier, cost).

    Returns:
        Formatted markdown PR body.
    """
    sections = []

    # Summary
    sections.append(f"## \U0001f4cb Summary\n\n{summary}")

    # Changelog
    changelog_lines = _format_changelog(commits, urls)
    if changelog_lines:
        sections.append(f"## \U0001f4dd Changelog\n\n" + "\n".join(changelog_lines))

    # Changes table
    file_rows = _format_file_table(diff_stat, urls)
    if file_rows:
        sections.append(
            f"## \U0001f4ca Changes\n\n| File | Lines |\n|------|-------|\n"
            + "\n".join(file_rows)
        )

    # References — with labor attribution
    task_url = urls.task or ""
    compare_url = urls.compare or ""
    ref_lines = [
        f"## \U0001f517 References\n",
        "| | |",
        "|---|---|",
        f"| **Task** | [{task_id[:8]}]({task_url}) |",
        f"| **Agent** | {agent_name} |",
        f"| **Branch** | [`{_branch_from_urls(urls)}`]({compare_url}) |",
    ]
    if labor_stamp:
        tier_emoji = {
            "expert": "\U0001f7e2", "standard": "\U0001f535",
            "trainee": "\U0001f7e1", "community": "\U0001f7e0",
            "hybrid": "\U0001f534",
        }
        emoji = tier_emoji.get(labor_stamp.confidence_tier, "\u26aa")
        ref_lines.extend([
            f"| **Backend** | `{labor_stamp.backend}` |",
            f"| **Model** | `{labor_stamp.model}` |",
            f"| **Confidence** | {emoji} {labor_stamp.confidence_tier} |",
            f"| **Effort** | {labor_stamp.effort} |",
        ])
        if labor_stamp.estimated_cost_usd:
            ref_lines.append(
                f"| **Est. Cost** | ${labor_stamp.estimated_cost_usd:.4f} |"
            )
        if labor_stamp.is_trainee:
            ref_lines.append(
                f"| **⚠️ Trainee** | This output requires extra review scrutiny |"
            )
    sections.append("\n".join(ref_lines))

    # Trainee warning — prominent if non-expert model
    if labor_stamp and labor_stamp.trainee_warning:
        sections.append(f"> {labor_stamp.trainee_warning}")

    # Footer — with provenance line
    stamp_label = labor_stamp.provenance_line if labor_stamp else ""
    footer_parts = ["Generated by OpenClaw Fleet"]
    if stamp_label:
        footer_parts.append(stamp_label)
    footer_text = " \u00b7 ".join(footer_parts)
    sections.append(f"---\n<sub>{footer_text}</sub>")

    return "\n\n".join(sections)


def format_pr_title(agent_name: str, task_title: str) -> str:
    """Build the PR title."""
    return f"fleet({agent_name}): {task_title}"


def _format_changelog(commits: list[Commit], urls: ResolvedUrls) -> list[str]:
    """Format commits as changelog entries."""
    emoji_map = {
        "feat": "\u2728", "fix": "\U0001f41b", "docs": "\U0001f4da",
        "test": "\U0001f9ea", "refactor": "\u267b\ufe0f", "chore": "\U0001f527",
        "ci": "\U0001f504", "style": "\U0001f3a8", "perf": "\u26a1",
    }
    lines = []
    commit_urls = {c["sha"]: c["url"] for c in (urls.commits or [])}

    for commit in commits:
        emoji = emoji_map.get(
            commit.commit_type.value if commit.commit_type else "", "\U0001f4dd"
        )
        sha_url = commit_urls.get(commit.sha, "")
        sha_link = (
            f"[`{commit.short_sha}`]({sha_url})" if sha_url
            else f"`{commit.short_sha}`"
        )
        lines.append(f"- {emoji} {commit.message} ({sha_link})")

    return lines


def _format_file_table(
    diff_stat: list[dict], urls: ResolvedUrls
) -> list[str]:
    """Format diff stat as a markdown table."""
    file_urls = {f["path"]: f["url"] for f in (urls.files or [])}
    rows = []

    for f in diff_stat:
        path = f["path"]
        url = file_urls.get(path, "")
        link = f"[`{path}`]({url})" if url else f"`{path}`"
        rows.append(f"| {link} | +{f['added']}/-{f['removed']} |")

    return rows


def _branch_from_urls(urls: ResolvedUrls) -> str:
    """Extract branch name from compare URL."""
    if urls.compare and "..." in urls.compare:
        return urls.compare.split("...")[-1]
    return ""