"""Fleet PR body formatter.

Produces publication-quality PR descriptions with changelog,
diff table, and cross-references.
"""

from __future__ import annotations

from fleet.core.models import Commit
from fleet.core.urls import ResolvedUrls


def format_pr_body(
    *,
    summary: str,
    commits: list[Commit],
    diff_stat: list[dict],
    urls: ResolvedUrls,
    task_id: str,
    task_title: str,
    agent_name: str,
) -> str:
    """Build a rich PR body from task data.

    Args:
        summary: What was done and why.
        commits: Parsed commits on the branch.
        diff_stat: File changes [{path, added, removed}].
        urls: Resolved URLs for all references.
        task_id: MC task ID.
        task_title: MC task title.
        agent_name: Agent that did the work.

    Returns:
        Formatted markdown PR body.
    """
    sections = []

    # Summary
    sections.append(f"## 📋 Summary\n\n{summary}")

    # Changelog
    changelog_lines = _format_changelog(commits, urls)
    if changelog_lines:
        sections.append(f"## 📝 Changelog\n\n" + "\n".join(changelog_lines))

    # Changes table
    file_rows = _format_file_table(diff_stat, urls)
    if file_rows:
        sections.append(
            f"## 📊 Changes\n\n| File | Lines |\n|------|-------|\n"
            + "\n".join(file_rows)
        )

    # References
    task_url = urls.task or ""
    compare_url = urls.compare or ""
    sections.append(
        f"## 🔗 References\n\n"
        f"| | |\n|---|---|\n"
        f"| **Task** | [{task_id[:8]}]({task_url}) |\n"
        f"| **Agent** | {agent_name} |\n"
        f"| **Branch** | [`{_branch_from_urls(urls)}`]({compare_url}) |"
    )

    # Footer
    sections.append("---\n<sub>Generated by OpenClaw Fleet</sub>")

    return "\n\n".join(sections)


def format_pr_title(agent_name: str, task_title: str) -> str:
    """Build the PR title."""
    return f"fleet({agent_name}): {task_title}"


def _format_changelog(commits: list[Commit], urls: ResolvedUrls) -> list[str]:
    """Format commits as changelog entries."""
    emoji_map = {
        "feat": "✨", "fix": "🐛", "docs": "📚", "test": "🧪",
        "refactor": "♻️", "chore": "🔧", "ci": "🔄",
        "style": "🎨", "perf": "⚡",
    }
    lines = []
    commit_urls = {c["sha"]: c["url"] for c in (urls.commits or [])}

    for commit in commits:
        emoji = emoji_map.get(
            commit.commit_type.value if commit.commit_type else "", "📝"
        )
        sha_url = commit_urls.get(commit.sha, "")
        sha_link = (
            f"[`{commit.short_sha}`]({sha_url})" if sha_url
            else f"`{commit.short_sha}`"
        )
        lines.append(f"- {emoji} {commit.message} ({sha_link})")

    return lines


def _format_file_table(
    diff_stat: list[dict], urls: ResolvedUrls
) -> list[str]:
    """Format diff stat as a markdown table."""
    file_urls = {f["path"]: f["url"] for f in (urls.files or [])}
    rows = []

    for f in diff_stat:
        path = f["path"]
        url = file_urls.get(path, "")
        link = f"[`{path}`]({url})" if url else f"`{path}`"
        rows.append(f"| {link} | +{f['added']}/-{f['removed']} |")

    return rows


def _branch_from_urls(urls: ResolvedUrls) -> str:
    """Extract branch name from compare URL."""
    if urls.compare and "..." in urls.compare:
        return urls.compare.split("...")[-1]
    return ""