#!/usr/bin/env bash
set -euo pipefail

# Push enhanced SOUL.md and .claude/settings.json to MC-provisioned agent workspaces.
# Combines agent role (from agents/<name>/SOUL.md) with MC workflow instructions.
# Also ensures Claude Code permissions are set for each workspace.
#
# Only operates on CURRENT MC agent workspaces — stale workspaces from
# previous setup runs are cleaned up automatically.

FLEET_DIR="$(cd "$(dirname "$0")/.." && pwd)"
AGENTS_DIR="$FLEET_DIR/agents"
WORKFLOW="$AGENTS_DIR/_template/MC_WORKFLOW.md"
TEMPLATE_SETTINGS="$AGENTS_DIR/_template/.claude/settings.json"

if [[ ! -f "$WORKFLOW" ]]; then
    echo "ERROR: $WORKFLOW not found"
    exit 1
fi

set -a
source "$FLEET_DIR/.env" 2>/dev/null || true
set +a

# Get current MC agent IDs — only these workspaces are valid
CURRENT_IDS=""
if [[ -n "${LOCAL_AUTH_TOKEN:-}" ]]; then
    CURRENT_IDS=$(curl -sf -m 10 -H "Authorization: Bearer $LOCAL_AUTH_TOKEN" \
        "http://localhost:${BACKEND_PORT:-8000}/api/v1/agents" 2>/dev/null \
        | python3 -c "
import json, sys
data = json.load(sys.stdin)
items = data.get('items', data) if isinstance(data, dict) else data
for a in items:
    if 'Gateway' not in a.get('name', ''):
        print(a['id'])
" 2>/dev/null || true)
fi

# Clean up stale workspaces from previous setup runs
if [[ -n "$CURRENT_IDS" ]]; then
    cleaned=0
    for workspace in "$FLEET_DIR"/workspace-mc-*; do
        [[ -d "$workspace" ]] || continue
        ws_id=$(basename "$workspace" | sed 's/workspace-mc-//')
        if ! echo "$CURRENT_IDS" | grep -q "$ws_id"; then
            rm -rf "$workspace"
            cleaned=$((cleaned + 1))
        fi
    done
    if [[ "$cleaned" -gt 0 ]]; then
        echo "Cleaned $cleaned stale workspaces"
    fi
fi

updated=0
skipped=0

for workspace in "$FLEET_DIR"/workspace-mc-*; do
    [[ -d "$workspace" ]] || continue

    # Extract agent name — try TOOLS.md first, fallback to .mcp.json
    agent_name=$(grep 'AGENT_NAME=' "$workspace/TOOLS.md" 2>/dev/null | sed 's/.*`AGENT_NAME=//' | sed 's/`//' | tr -d '[:space:]' || true)
    if [[ -z "$agent_name" ]]; then
        # Fallback: read from .mcp.json FLEET_AGENT env var
        agent_name=$(python3 -c "import json; print(json.load(open('$workspace/.mcp.json'))['mcpServers']['fleet']['env']['FLEET_AGENT'])" 2>/dev/null || true)
    fi
    if [[ -z "$agent_name" ]]; then
        skipped=$((skipped + 1))
        continue
    fi

    # Find the agent's role SOUL.md
    role_soul="$AGENTS_DIR/$agent_name/SOUL.md"
    [[ ! -f "$role_soul" ]] && role_soul="$AGENTS_DIR/$agent_name/CLAUDE.md"
    if [[ ! -f "$role_soul" ]]; then
        echo "SKIP: $agent_name (no SOUL.md or CLAUDE.md)"
        skipped=$((skipped + 1))
        continue
    fi

    # Combine: role + standards + workflow
    {
        cat "$role_soul"
        echo ""
        [[ -f "$AGENTS_DIR/_template/STANDARDS.md" ]] && cat "$AGENTS_DIR/_template/STANDARDS.md" && echo ""
        cat "$WORKFLOW"
    } > "$workspace/SOUL.md"

    # Ensure .claude directory exists
    # NOTE: settings.json is managed by configure-agent-settings.sh (with hooks)
    # Do NOT overwrite it here — that script reads agent-hooks.yaml and
    # generates proper JSON with effort, permissions, and hooks.
    mkdir -p "$workspace/.claude"

    # Deploy .mcp.json — prefer per-agent (has role MCP servers), fallback to template
    AGENT_MCP="$AGENTS_DIR/$agent_name/mcp.json"
    MCP_TEMPLATE="$AGENTS_DIR/_template/mcp.json"
    if [[ -f "$AGENT_MCP" ]]; then
        # Per-agent mcp.json generated by setup-agent-tools.sh from config/agent-tooling.yaml
        # Contains fleet MCP server + role-specific servers (filesystem, github, playwright, etc.)
        cp "$AGENT_MCP" "$workspace/.mcp.json"
    elif [[ -f "$MCP_TEMPLATE" ]]; then
        # Fallback: template with fleet MCP server only
        sed \
            -e "s|{{FLEET_VENV}}|$FLEET_DIR/.venv|g" \
            -e "s|{{FLEET_DIR}}|$FLEET_DIR|g" \
            -e "s|{{AGENT_NAME}}|$agent_name|g" \
            -e "s|{{WORKSPACE}}|$workspace|g" \
            "$MCP_TEMPLATE" > "$workspace/.mcp.json"
    fi

    # Symlink gateway operation skills into agent workspace (.agents/skills/)
    FLEET_GATEWAY_SKILLS="$FLEET_DIR/.agents/skills"
    if [[ -d "$FLEET_GATEWAY_SKILLS" ]]; then
        mkdir -p "$workspace/.agents"
        # Remove stale symlink if target changed
        if [[ -L "$workspace/.agents/skills" ]]; then
            rm "$workspace/.agents/skills"
        fi
        if [[ ! -e "$workspace/.agents/skills" ]]; then
            ln -s "$FLEET_GATEWAY_SKILLS" "$workspace/.agents/skills"
        fi
    fi

    # Symlink fleet workflow skills into agent workspace (.claude/skills/)
    FLEET_WORKFLOW_SKILLS="$FLEET_DIR/.claude/skills"
    if [[ -d "$FLEET_WORKFLOW_SKILLS" ]]; then
        mkdir -p "$workspace/.claude"
        # Remove stale symlink if target changed
        if [[ -L "$workspace/.claude/skills" ]]; then
            rm "$workspace/.claude/skills"
        fi
        if [[ ! -e "$workspace/.claude/skills" ]]; then
            ln -s "$FLEET_WORKFLOW_SKILLS" "$workspace/.claude/skills"
        fi
    fi

    # Deploy role-aware sub-agents from config/agent-tooling.yaml
    # Each agent gets default sub-agents + their role-specific ones
    FLEET_AGENTS_SRC="$FLEET_DIR/.claude/agents"
    TOOLING_YAML="$FLEET_DIR/config/agent-tooling.yaml"
    if [[ -d "$FLEET_AGENTS_SRC" && -f "$TOOLING_YAML" ]]; then
        AGENT_SUBAGENTS_DIR="$workspace/.claude/agents"
        mkdir -p "$AGENT_SUBAGENTS_DIR"

        # Get the list of sub-agents for this role (defaults + role-specific)
        SUBAGENT_LIST=$("$FLEET_DIR/.venv/bin/python" - "$agent_name" "$TOOLING_YAML" << 'PYSUBAGENTS'
import sys, yaml

agent_name = sys.argv[1]
tooling_file = sys.argv[2]

with open(tooling_file) as f:
    config = yaml.safe_load(f) or {}

# Collect default + role-specific sub-agents
agents = []
for sa in config.get("defaults", {}).get("sub_agents", []):
    agents.append(sa)
for sa in config.get("agents", {}).get(agent_name, {}).get("sub_agents", []):
    if sa not in agents:
        agents.append(sa)

for a in agents:
    print(a)
PYSUBAGENTS
        )

        # Clean existing symlinks (remove stale ones)
        for existing in "$AGENT_SUBAGENTS_DIR"/*.md; do
            [[ -L "$existing" ]] && rm "$existing"
        done 2>/dev/null

        # Create symlinks for each sub-agent
        sa_count=0
        while IFS= read -r sa_name; do
            [[ -z "$sa_name" ]] && continue
            SA_SRC="$FLEET_AGENTS_SRC/$sa_name.md"
            if [[ -f "$SA_SRC" ]]; then
                ln -sf "$SA_SRC" "$AGENT_SUBAGENTS_DIR/$sa_name.md"
                sa_count=$((sa_count + 1))
            fi
        done <<< "$SUBAGENT_LIST"
    fi

    echo "OK: $agent_name (sub-agents: ${sa_count:-0})"
    updated=$((updated + 1))
done

echo ""
echo "Updated: $updated, Skipped: $skipped"
